development:
  name: pin-website
  url: http://dev.website.2010.mindpin.com/
  master_url: http://dev.config-manager.2010.mindpin.com/

test:
  name: pin-website
  url: http://dev.website.2010.mindpin.com/
  master_url: http://dev.config-manager.2010.mindpin.com/

production:
  name: pin-website
  url: http://website.2010.mindpin.com/
  master_url: http://dev.config-manager.2010.mindpin.com/
